name: Publish Training Operator SDK Images

on:
  - push
  - pull_request

jobs:
  core:
    name: Publish Image
    uses: ./.github/workflows/build-and-publish-images.yaml
    with:
      component-name: ${{ matrix.component-name }}
      platforms: linux/amd64,linux/arm64,linux/ppc64le
      dockerfile: ${{ matrix.dockerfile }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - component-name: train-api-hf-image
            dockerfile: sdk/python/kubeflow/trainer/hf_dockerfile
            context: sdk/python/kubeflow/trainer
